apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app-argo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sidhuni/Demo-app.git
<<<<<<< HEAD
    targetRevision: HEAD
    path: templates         # ðŸ‘ˆ path to your Helm chart folder inside the repo
=======
    targetRevision: main
    path:templates         # ðŸ‘ˆ path to your Helm chart folder inside the repo
>>>>>>> 83906cc674bafd32830022b2a453fd68e0499adc
    helm:
      releaseName: demo
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
