apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-app.fullname" . }}-config
data:
  app.properties: |
    database_url={{ .Values.database.url }}
    log_level={{ .Values.app.logLevel }}